package org.scbit.lsbi.protein.pojo;

// Generated 2012-8-3 11:42:12 by Hibernate Tools 3.4.0.CR1

/**
 * IdmapPart generated by hbm2java
 */
public class IdmapPart implements java.io.Serializable {

	private Short dbsId;
	private String id;
	private String geneidAc;
	
	public IdmapPart() {
		// TODO Auto-generated constructor stub
	}

	public IdmapPart(Short dbsId, String id, String geneidAc) {
		super();
		this.dbsId = dbsId;
		this.id = id;
		this.geneidAc = geneidAc;
	}

	public Short getDbsId() {
		return this.dbsId;
	}

	public void setDbsId(Short dbsId) {
		this.dbsId = dbsId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getGeneidAc() {
		return this.geneidAc;
	}

	public void setGeneidAc(String geneidAc) {
		this.geneidAc = geneidAc;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IdmapPart other = (IdmapPart) obj;
		if (dbsId == null) {
			if (other.dbsId != null)
				return false;
		} else if (!dbsId.equals(other.dbsId))
			return false;
		if (geneidAc == null) {
			if (other.geneidAc != null)
				return false;
		} else if (!geneidAc.equals(other.geneidAc))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dbsId == null) ? 0 : dbsId.hashCode());
		result = prime * result
				+ ((geneidAc == null) ? 0 : geneidAc.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "IdmapPart [dbsId=" + dbsId + ", id=" + id + ", geneidAc="
				+ geneidAc + "]";
	}

}
